# Karl Daniel P. De Mesa - Lab1 Activity(Expense Tracker)
print("=" * 40)
print("\t     EXPENSE TRACKER")
print("\t   Know Your Expenses")
print("=" * 40)
print("\nWelcome! This is your personal Expense Tracker!\n")
print("MAIN MENU")
print("   1. Add Expense        \t\t(coming soon)")
print("   2. View Expenses      \t\t(coming soon)")
print("   3. Show Total Expenses\t\t(coming soon)")
print("   4. Exit               \t\t(coming soon)")
print("-" * 40)
print("Made By: Karl Daniel P. De Mesa  |  Installment 1")
print("=" * 40)
print("\n\n")